services:
  
  # Type 1
  ## To add tartget-services-orange to a particular vpn network with a specified ip
  target-services-orange:
    image: target_image
    network_mode: service:wireguard

  # Type 2
  ## To add target-service-apple to a particular vpn network with connectivity but have diff ip
  target-services-apple:
    image: target_image
    networks:
      - vpn

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/wg_confs:/config/wg_confs 
      - /lib/modules:/lib/modules 
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

networks:
  vpn: